name: ESLint Code Analysis

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        run: npm install --prefix ./frontend

      - name: Create reports directory
        run: mkdir -p frontend/reports

      - name: Install ESLint SARIF Formatter
        run: npm install --prefix ./frontend @microsoft/eslint-formatter-sarif --save-dev

      - name: Run ESLint with SARIF output
        working-directory: ./frontend
        run: npx eslint ./src --format @microsoft/eslint-formatter-sarif --output-file=reports/eslint-results.sarif || true

      - name: Debug ESLint Output
        run: cat frontend/reports/eslint-results.sarif || echo "No SARIF report generated"
      
      - name: Upload ESLint report artifact
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: frontend/reports/eslint-results.sarif