name: Test and Deploy to Cloud

on:
  push:
    branches:
      - Deployment

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      # FRONTEND BUILD
      - name: Install dependencies and building Frontend
        run: |
          npm install --prefix ./frontend
          npm run build --prefix ./frontend

      # BACKEND BUILD
      - name: Publish backend
        working-directory: ./backend/MyWebApp
        run: dotnet publish -c Release -o publish

      # SET UP SSH KEY FOR RSYNC
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLOUD_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.CLOUD_HOST }} >> ~/.ssh/known_hosts

      # DEPLOY TO CLOUD SERVER
      - name: Upload frontend using RSYNC
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./frontend/build ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_HOST }}:/home/dev/SSD/testing_deploy/frontend/

      - name: Upload backend using RSYNC
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./backend/MyWebApp/publish/ ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_HOST }}:/home/dev/SSD/testing_deploy/backend/

