name: Build and Push Frontend

on:
  push:
    branches:
      - Deployment
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # FRONTEND BUILD
      - name: Install dependencies
        run: 
          npm install --prefix ./frontend
      
      - name: Building frontend
        run:  
          npm run build --prefix ./frontend

      # SET UP SSH KEY FOR RSYNC
      - name: Set up SSH key
        run: |
          echo "Cloud host is: ${{ secrets.CLOUD_HOST }}"
          echo "Cloud user is: ${{ secrets.CLOUD_USER }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.CLOUD_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.CLOUD_HOST }} >> ~/.ssh/known_hosts

      # DEPLOY TO CLOUD SERVER
      - name: Upload frontend using RSYNC
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./frontend/build ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_HOST }}:/home/dev/SSD/testing_deploy/frontend/
